 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package register;
import register.Message;
import register.JsonStorage;
import javax.swing.*;
import javax.swing.JOptionPane;
import java.util.Scanner;

/**
 *
 * @author 27743
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
         System.out.println("=================================================================================================");
        System.out.println("=====================================PART2=======================================================");
        System.out.println("=================================================================================================");
        
        JOptionPane.showMessageDialog(null," Welcome To QuickChat.");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jButton1.setBackground(new java.awt.Color(255, 102, 204));
        jButton1.setText("Select Option");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QuickChat");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Home Page");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       Scanner input = new Scanner(System.in);  
        int OptionNumber=0;
      
     while(OptionNumber!=3) 
     {
         int numberOfId=1000000000;
        
// welcome message and the menu option are displayed
        
        int option=Integer.parseInt(JOptionPane.showInputDialog(null,"Choose the following option\n"
              + "1. send message\n"
              + "2. recently sent messages\n"
              + "3. Quit"));
      
        OptionNumber=option;
        
      if(option==1)
      {
 //the user should select the number of messages that them wish to send 
          int NumberOfMessage=Integer.parseInt(JOptionPane.showInputDialog(null,"How Many Messages You Wish To Send?" ));
          
 //used the for loop user to enter the assigned number of messages
           for(int i=1;i<=NumberOfMessage;i++)
           {
               
              
           
          if(NumberOfMessage>0)
          {
           
            int NumberMessageSent=0;
 //ensures that the user enters the correct recipient SA Celphone number 
             String SentToNumber=JOptionPane.showInputDialog(null," Please Add The Cellphone Number ");
             
             
           boolean checkcellphonenumber=SentToNumber.contains("+27")&&SentToNumber.length()<13 && SentToNumber.length()>11;
       if(checkcellphonenumber)
       {
           System.out.println("Sent to SA cellphone number: "+SentToNumber);
           JOptionPane.showMessageDialog(null,"Cell Phone Number Successfully Added");
      
//allows the user to enter necessary message details     
           String message=JOptionPane.showInputDialog(null,"Text The Message", SentToNumber,JOptionPane.PLAIN_MESSAGE);
           
 //using counter loop to track the message ID
      
           int counter=i;
           int MessageId=numberOfId +counter;
           
           
           
           System.out.println("the messege ID: "+ MessageId); 
          
           //
           
 //using counter to track the number of messages sent
 
      int MessageSent=NumberMessageSent +i;
     
           System.out.println("number of messages sent: "+MessageSent);
      
           if(message.length()<250)
           {
               System.out.println("the message length is correct");
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Please enter a message of less than 50 characters");
           }
           
           //used String NumberOfId to convert numberOfId which is a int into String
     String NumberOfId =String.valueOf(numberOfId);
     
//using String manipulation(substring) to find the first two numbers of numberId
     String FirstTwoNumbers=NumberOfId.substring(0,2);
           System.out.println("the first two numbers of messageId: "+ FirstTwoNumbers);
           
           
//created a string manipulation(substring) to separate the first and the last word in the message
           String[] words=message.split("\\s+");
      if(words.length>0)
      {
          String FirstWord = words[0];
          String lastWord = words[words.length-1];
          System.out.println("the first name: "+ FirstWord);
          System.out.println("the last name: "+ lastWord);
          
// the message hash is created using String manipulation(substring) and will be displayed
           System.out.println("Message Hash: "+FirstTwoNumbers+":"+MessageSent+":"+FirstWord+lastWord);
           System.out.println("=================================================================================================");
          
           
      
      
      int MessageOption=Integer.parseInt(JOptionPane.showInputDialog(null,"Select the following options \n"
              + "1. send message\n"
              + "2. diregard message\n"
              + "3. store message "));
          
            if(MessageOption==1)
           {
//display message hash in the correctly
//string manipulation will be displayed 
               JOptionPane.showMessageDialog(null,"Message ID: "+MessageId
                       + "\n Message Hash: "+FirstTwoNumbers+":"+MessageSent+":"+FirstWord+lastWord
                       + "\n Recipient: "+SentToNumber
                       + "\n Message: "+message);
               
               JOptionPane.showMessageDialog(null,"Message Sent");
               
               JOptionPane.showMessageDialog(null,MessageSent+" Messages sent");
           }
            else if(MessageOption==2)
            {
            int delete=0;
                 int DeleteMessage=JOptionPane.showOptionDialog(null,"ARE YOU SURE YOU WANNA DELETE MESSAGE","select ",0,delete,null,null,null);
                  
                 if(DeleteMessage==0)
                 {
                     NumberOfMessage--;
                     MessageSent--;
                     MessageId--;
                     JOptionPane.showMessageDialog(null,"Message SuccessFully Deleted");
                     JOptionPane.showMessageDialog(null,MessageSent--+" Message Sent");
                     
                     
                 }
                 else if(DeleteMessage==1)
                 {
                     JOptionPane.showMessageDialog(null,"Message Not SuccessFully Deleted");
                 }
                 
            }
            else if(MessageOption==3)
            {
                 JOptionPane.showMessageDialog(null,"Message ID: "+MessageId
                       + "\n Message Hash: "+FirstTwoNumbers+":"+MessageSent+":"+FirstWord+lastWord
                       + "\n Recipient: "+SentToNumber
                       + "\n Message: "+message);
 // 1) Build the Message object
 //using ChartGPT to generate code to store messages
Message msgObj = new Message(
    MessageId,
    MessageSent,
    SentToNumber,
    message,
    FirstTwoNumbers + ":" + MessageSent + ":" + FirstWord + lastWord
);

// 2) Persist it
JsonStorage.saveMessage(msgObj);

// 3) Notify the user
JOptionPane.showMessageDialog(null,
    "Message stored successfully to messages.json");
JOptionPane.showMessageDialog(null,MessageSent+" Messages sent");
            }
      
       }
       else
       {
           System.out.println("incorrect SA cellphone number");
           JOptionPane.showMessageDialog(null,"Cell phone number incorrectly formatted or does not contain international code");
           return ;//stop execution if mobile number is invalid
      
       }
     
       
    }
      
      }
           }   
          
      }
      //end of for loop
     
      
      else if(option==2)
      {
          JOptionPane.showMessageDialog(null,"Coming Soon");
      }
      else if(option==3)
      {
          JOptionPane.showMessageDialog(null,"Exiting QuickChat.GoodBye");
          System.exit(0);
      }
      else
      {
          JOptionPane.showMessageDialog(null,"Please enter from the above Options");
      }
      
     } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
                
                
            }
        });
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
